version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: biomaterial-labs-API
    command: ["/biomaterial-labs-API/docker/app.sh"]
    ports:
      - 80:8000
    depends_on:
      db:
        condition: service_healthy



volumes:
  db-data: