version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d test -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: 
      context: .
    stdin_open: true 
    tty: true
    env_file:
      - .env
    container_name: biomaterial-labs-API
    depends_on:
      db:
        condition: service_healthy
