from ..generic_lab_table_repository import GenericLabTableRepository
from .models import StyrolPolymerizationBulkORM
from .schemas import StyrolPolymerizationBulkDTO


class StyrolPolymerizationBulkRepository(GenericLabTableRepository[StyrolPolymerizationBulkORM, StyrolPolymerizationBulkDTO]):
    pass

styrol_polymerization_bulk_repository = StyrolPolymerizationBulkRepository(StyrolPolymerizationBulkORM)
