"""Add summary table

Revision ID: dda4002b9f73
Revises: 3cf05f117b68
Create Date: 2024-04-04 15:05:34.926797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda4002b9f73'
down_revision: Union[str, None] = '3cf05f117b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_table',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('styrol_polymerization_bulk_status', sa.Boolean(), nullable=False),
    sa.Column('styrol_polymerization_bulk_mark', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('summary_table')
    # ### end Alembic commands ###
